// Templates
export { default as TemplatesSvg } from './Templates'
export { default as BoardTemplateSvg } from './BoardTemplate'
export { default as CalendarTemplateSvg } from './CalendarTemplate'
export { default as TableTemplateSvg } from './TableTemplate'
export { default as TaskListTemplateSvg } from './TaskListTemplate'

// Options
export { default as EmptyPageIconSvg } from './EmptyPageIcon'
export { default as EmptyWithIconSvg } from './EmptyWithIcon'
export { default as LinkSvg } from './Link'
export { default as RenameSvg } from './Rename'
export { default as DeleteTrashSvg } from './DeleteTrash'
export { default as FavoriteStarSvg } from './FavoriteStar'
export { default as UnfavoriteStarSvg } from './UnfavoriteStar'
export { default as RemoveFavoriteSvg } from './RemoveFavorite'
export { default as DuplicateSvg } from './Duplicate'
export { default as TrashSvg } from './Trash'
export { default as LockPageSvg } from './LockPage'
export { default as UnlockPageSvg } from './UnlockPage'
export { default as CustomizePageSvg } from './CustomizePage'
export { default as MoveToSvg } from './MoveTo'
export { default as OptionsDotsSvg } from './OptionsDots'
export { default as PencilSvg } from './Pencil'
export { default as SettingsGearSvg } from './SettingsGear'
export { default as ClockSvg } from './Clock'
export { default as SidebarLoupeSvg } from './SidebarLoupe'
export { default as DragContentItemSvg } from './DragContentItem'
export { default as ColorBlockSvg } from './ColorBlock'

// Decoration
export { default as AddCommentSvg } from './AddComment'
export { default as CoverSvg } from './Cover'
export { default as SmileySvg } from './Smiley'
export { default as CheckSvg } from './Check'
export { default as ThinCheckSvg } from './ThinCheck'
export { default as ChevronDownSvg } from './ChevronDown'
export { default as DoubleChevronSvg } from './DoubleChevron'
export { default as EmptyCommentsSvg } from './EmptyComments'
export { default as HeaderCommentsSvg } from './HeaderComments'
export { default as UndoSvg } from './Undo'
export { default as TriangleSvg } from './Triangle'
export { default as QuickSearchLoupeSvg } from './QuickSearchLoupe'
export { default as EnterSvg } from './Enter'
export { default as ClearInputSvg } from './ClearInput'
export { default as PlusSvg } from './Plus'
export { default as SendArrowSvg } from './SendArrow'
export { default as AttachFileSvg } from './AttachFile'
export { default as CircleCheckFilledSvg } from './CircleCheckFilled'
export { default as CircleSvg } from './Circle'
export { default as CalendarSvg } from './Calendar'
export { default as AppleLogoSvg } from './AppleLogo'
export { default as GoogleLogoSvg } from './GoogleLogo'
export { default as BookSvg } from './Book'
export { default as CheckboxSquareSvg } from './CheckboxSquare'
