export { default as TemplatesSVG } from './Templates'
export { default as BoardTemplateSVG } from './BoardTemplate'
export { default as CalendarTemplateSVG } from './CalendarTemplate'
export { default as TableTemplateSVG } from './TableTemplate'
export { default as TaskListTemplateSVG } from './TaskListTemplate'
export { default as EmptyPageIconSVG } from './EmptyPage'
export { default as EmptyWithIconSVG } from './EmptyWithIcon'
export { default as LinkSVG } from './Link'
