// Templates
export { default as TemplatesSvg } from './Templates'
export { default as BoardTemplateSvg } from './BoardTemplate'
export { default as CalendarTemplateSvg } from './CalendarTemplate'
export { default as TableTemplateSvg } from './TableTemplate'
export { default as TaskListTemplateSvg } from './TaskListTemplate'

// Options
export { default as EmptyPageIconSvg } from './EmptyPageIcon'
export { default as EmptyWithIconSvg } from './EmptyWithIcon'
export { default as LinkSvg } from './Link'
export { default as RenameSvg } from './Rename'
export { default as DeleteTrashSvg } from './DeleteTrash'
export { default as FavoriteStarSvg } from './FavoriteStar'
export { default as UnfavoriteStarSvg } from './UnfavoriteStar'
export { default as RemoveFavoriteSvg } from './RemoveFavorite'
export { default as DuplicateSvg } from './Duplicate'
export { default as TrashSvg } from './Trash'
export { default as LockPageSvg } from './LockPage'
export { default as UnlockPageSvg } from './UnlockPage'
export { default as CustomizePageSvg } from './CustomizePage'
export { default as MoveToSvg } from './MoveTo'
export { default as OptionsDotsSvg } from './OptionsDots'

// Decoration
export { default as AddCommentSvg } from './AddComment'
export { default as AddCoverSvg } from './AddCover'
export { default as AddIconSvg } from './AddIcon'
export { default as CheckSvg } from './Check'
export { default as ChevronDownSvg } from './ChevronDown'
export { default as DoubleChevronSvg } from './DoubleChevron'
export { default as EmptyCommentsSvg } from './EmptyComments'
export { default as HeaderCommentsSvg } from './HeaderComments'
export { default as UndoSvg } from './Undo'
export { default as TriangleSvg } from './Triangle'
